"""empty message

Revision ID: 56d2d56b5dd7
Revises: f67f36e0ce07
Create Date: 2025-07-29 11:05:54.272339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d2d56b5dd7'
down_revision = 'f67f36e0ce07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
